### ISSUE TITLE
Support HTTP response trailers

### ISSUE THREAD

**Issue by jitsni** [reaktivity/nukleus-http2.java#13]
Some of the requirements:
* Implementing trailers lifecycle: HEADERS, DATA, HEADERS
"   Trailing header fields are carried in a header block that also
   terminates the stream.  Such a header block is a sequence starting
   with a HEADERS frame, followed by zero or more CONTINUATION frames,
   where the HEADERS frame bears an END_STREAM flag"
* Pseudo-header fields MUST NOT appear in trailers
* The HEADERS frame starting the trailers header block has the END_STREAM flag set.

**Comment by jfallows** [comment]
Implemented by #117
