### ISSUE TITLE
Use canonical :authority header when routing requests

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-http2.java#42]
How/can we route the http2 nukeli by `:authority` with out ports?  It looks like ports are required right now?  Should routing be based on scheme so the default port can be implied?

**Comment by jfallows** [comment]
The `http2` nukleus should route based on the canonical `:authority` even if the `BEGIN` extension or `ROUTE` extension `:authority` header is presented in non-canonical form.

**Comment by jfallows** [comment]
Fixed in ab067f41b183fe381dbe11dfa7af837659387e41.
